# Generated by Django 4.0.4 on 2022-05-05 14:44

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=funcionarios.models.uploadImage)),
            ],
        ),
    ]
